### ISSUE TITLE
Flag Listings

### ISSUE THREAD

**Issue by wopian** [wopian/hatayama#14]
- [ ] Implement
  - [x] National
  - [x] Prefecture
  - [ ] City
  - [ ] Government
  - [ ] Military
- [x] Style
- [x] Hook up to data source

**Comment by aleen42** [comment]
Are you from Japan?

**Comment by wopian** [comment]
@aleen42 nah, i'm British 😄

**Comment by aleen42** [comment]
@wopian _(: 」∠)_
